import { palette } from 'primevue/theme';
import accordion from 'primevue/theme/lara/accordion';
import autocomplete from 'primevue/theme/lara/autocomplete';
import avatar from 'primevue/theme/lara/avatar';
import badge from 'primevue/theme/lara/badge';
import blockui from 'primevue/theme/lara/blockui';
import breadcrumb from 'primevue/theme/lara/breadcrumb';
import button from 'primevue/theme/lara/button';
import calendar from 'primevue/theme/lara/calendar';
import card from 'primevue/theme/lara/card';
import carousel from 'primevue/theme/lara/carousel';
import cascadeselect from 'primevue/theme/lara/cascadeselect';
import checkbox from 'primevue/theme/lara/checkbox';
import chip from 'primevue/theme/lara/chip';
import chips from 'primevue/theme/lara/chips';
import colorpicker from 'primevue/theme/lara/colorpicker';
import confirmdialog from 'primevue/theme/lara/confirmdialog';
import confirmpopup from 'primevue/theme/lara/confirmpopup';
import contextmenu from 'primevue/theme/lara/contextmenu';
import datatable from 'primevue/theme/lara/datatable';
import dataview from 'primevue/theme/lara/dataview';
import dialog from 'primevue/theme/lara/dialog';
import divider from 'primevue/theme/lara/divider';
import dock from 'primevue/theme/lara/dock';
import dropdown from 'primevue/theme/lara/dropdown';
import editor from 'primevue/theme/lara/editor';
import fieldset from 'primevue/theme/lara/fieldset';
import fileupload from 'primevue/theme/lara/fileupload';
import galleria from 'primevue/theme/lara/galleria';
import global from 'primevue/theme/lara/global';
import image from 'primevue/theme/lara/image';
import inlinemessage from 'primevue/theme/lara/inlinemessage';
import inplace from 'primevue/theme/lara/inplace';
import inputgroup from 'primevue/theme/lara/inputgroup';
import inputnumber from 'primevue/theme/lara/inputnumber';
import inputswitch from 'primevue/theme/lara/inputswitch';
import inputtext from 'primevue/theme/lara/inputtext';
import listbox from 'primevue/theme/lara/listbox';
import megamenu from 'primevue/theme/lara/megamenu';
import menu from 'primevue/theme/lara/menu';
import menubar from 'primevue/theme/lara/menubar';
import message from 'primevue/theme/lara/message';
import multiselect from 'primevue/theme/lara/multiselect';
import orderlist from 'primevue/theme/lara/orderlist';
import organizationchart from 'primevue/theme/lara/organizationchart';
import overlaypanel from 'primevue/theme/lara/overlaypanel';
import paginator from 'primevue/theme/lara/paginator';
import panel from 'primevue/theme/lara/panel';
import panelmenu from 'primevue/theme/lara/panelmenu';
import password from 'primevue/theme/lara/password';
import picklist from 'primevue/theme/lara/picklist';
import progressbar from 'primevue/theme/lara/progressbar';
import progressspinner from 'primevue/theme/lara/progressspinner';
import radiobutton from 'primevue/theme/lara/radiobutton';
import rating from 'primevue/theme/lara/rating';
import scrollpanel from 'primevue/theme/lara/scrollpanel';
import scrolltop from 'primevue/theme/lara/scrolltop';
import selectbutton from 'primevue/theme/lara/selectbutton';
import sidebar from 'primevue/theme/lara/sidebar';
import skeleton from 'primevue/theme/lara/skeleton';
import slider from 'primevue/theme/lara/slider';
import speeddial from 'primevue/theme/lara/speeddial';
import splitbutton from 'primevue/theme/lara/splitbutton';
import splitter from 'primevue/theme/lara/splitter';
import steps from 'primevue/theme/lara/steps';
import tabmenu from 'primevue/theme/lara/tabmenu';
import tabview from 'primevue/theme/lara/tabview';
import tag from 'primevue/theme/lara/tag';
import terminal from 'primevue/theme/lara/terminal';
import tieredmenu from 'primevue/theme/lara/tieredmenu';
import timeline from 'primevue/theme/lara/timeline';
import toast from 'primevue/theme/lara/toast';
import togglebutton from 'primevue/theme/lara/togglebutton';
import toolbar from 'primevue/theme/lara/toolbar';
import tooltip from 'primevue/theme/lara/tooltip';
import tree from 'primevue/theme/lara/tree';
import treeselect from 'primevue/theme/lara/treeselect';
import treetable from 'primevue/theme/lara/treetable';

export default {
    variables: {
        primitive: {
            blue: palette('#3B82F6'),
            green: palette('#22C55E'),
            yellow: palette('#EAB308'),
            cyan: palette('#06B6D4'),
            pink: palette('#EC4899'),
            indigo: palette('#6366F1'),
            teal: palette('#14B8A6'),
            orange: palette('#F97316'),
            bluegray: palette('#64748B'),
            purple: palette('#A855F7'),
            red: palette('#FF3D32')
        },
        semantic: {
            hoverBg: 'rgba(255,255,255,.03)', // @todo dark
            fontFamily: '"Inter var", sans-serif',
            fontSize: '1rem',
            fontWeight: 'normal',
            textColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            textSecondaryColor: 'var(--p-dark-shade-100, var(--p-shade-600))',
            borderRadius: '6px',
            transitionDuration: '.2s',
            formElementTransition: 'background-color var(--p-transition-duration), color var(--p-transition-duration), border-color var(--p-transition-duration), box-shadow var(--p-transition-duration)',
            actionIconTransition: 'background-color var(--p-transition-duration), color var(--p-transition-duration), box-shadow var(--p-transition-duration)',
            listItemTransition: 'box-shadow var(--p-transition-duration)',
            primeIconFontSize: '1rem',
            divider: '1px solid var(--p-dark-shade-600, var(--p-shade-300))',
            inlineSpacing: '.5rem',
            disabledOpacity: 'var(.4, var(.6))', // @todo
            maskBg: 'var(rgba(0, 0, 0, 0.4), var(rgba(0, 0, 0, 0.4)))', // @todo
            loadingIconFontSize: '2rem',
            errorColor: 'var(#FCA5A5, var(#e24c4c))', // @todo
            scaleSM: '0.875',
            scaleLG: '1.25',
            focusOutlineColor: 'var(--p-dark-primary-lightest-color, var(--p-primary-light-color))',
            focusOutline: '0 none',
            focusOutlineOffset: '0',
            focusShadow: '0 0 0 .2rem var(--p-dark-focus-outline-color, var(--p-focus-outline-color))',
            actionIconWidth: '2rem',
            actionIconHeight: '2rem',
            actionIconBg: 'transparent',
            actionIconBorder: '0 none',
            actionIconColor: 'var(--p-dark-shade-100, var(--p-shade-600))',
            actionIconHoverBg: 'var(--p-dark-hover-bg, var(--p-shade-200))',
            actionIconHoverBorderColor: 'transparent',
            actionIconHoverColor: 'var(--p-dark-shade-0, var(--p-shade-800))',
            actionIconBorderRadius: '50%',
            inputPadding: '.75rem .75rem',
            inputTextFontSize: '1rem',
            inputBg: 'var(--p-dark-shade-900, var(--p-shade-0))',
            inputTextColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            inputIconColor: 'var(--p-dark-shade-100, var(--p-shade-600))',
            inputBorder: '1px solid var(--p-dark-shade-600, var(--p-shade-400))',
            inputHoverBorderColor: 'var(--p-dark-primary-color, var(--p-primary-color))',
            inputFocusBorderColor: 'var(--p-dark-primary-color, var(--p-primary-color))',
            inputErrorBorderColor: 'var(--p-dark-error-color, var(--p-error-color))',
            inputPlaceholderTextColor: 'var(--p-dark-shade-100, var(--p-shade-600))',
            inputFilledBg: 'var(--p-dark-shade-600, var(--p-shade-200))',
            inputFilledHoverBg: 'var(--p-dark-input-filled-bg, var(--p-input-filled-bg))',
            inputFilledFocusBg: 'var(--p-dark-input-filled-bg, var(--p-shade-0))',
            inputGroupBg: 'var(--p-dark-shade-800, var(--p-shade-200))',
            inputGroupTextColor: 'var(--p-dark-shade-100, var(--p-shade-600))',
            inputGroupAddOnMinWidth: '3rem',
            inputListBg: 'var(--p-dark-shade-800, var(--p-shade-0))',
            inputListTextColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            inputListBorder: 'var(--p-dark-input-border, var(--p-input-border))',
            inputListPadding: '.75rem 0',
            inputListItemPadding: '.75rem 1.25rem',
            inputListItemBg: 'transparent',
            inputListItemTextColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            inputListItemHoverBg: 'var(--p-dark-hover-bg, var(--p-shade-200))',
            inputListItemTextHoverColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            inputListItemFocusBg: 'var(--p-dark-shade-600, var(--p-shade-300))',
            inputListItemTextFocusColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            inputListItemBorder: '0 none',
            inputListItemBorderRadius: '0',
            inputListItemMargin: '0',
            inputListItemFocusShadow: 'inset 0 0 0 0.15rem var(--p-dark-focus-outline-color, var(--p-focus-outline-color))',
            inputListHeaderPadding: '.75rem 1.25rem',
            inputListHeaderMargin: '0',
            inputListHeaderBg: 'var(--p-dark-shade-800, var(--p-shade-100))',
            inputListHeaderTextColor: 'var(--p-dark-shade-0, var(--p-shade-800))',
            inputListHeaderBorder: '1px solid var(--p-dark-shade-600, var(--p-shade-300))',
            inputOverlayBg: 'var(--p-dark-input-list-bg, var(--p-input-list-bg))',
            inputOverlayHeaderBg: 'var(--p-dark-input-list-header-bg, var(--p-input-list-header-bg))',
            inputOverlayBorder: 'var(1px solid var(--p-dark-shade-600), var(0 none))', // @todo
            inputOverlayShadow: 'var(0 2px 4px -1px rgba(0,0,0,.2), 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12), var(0 2px 12px 0 rgba(0,0,0,.1)))', // @todo
            passwordMeterBg: 'var(--p-dark-shade-600, var(--p-shade-300))',
            passwordWeakBg: 'var(#eb9a9c, var(#ea5455))', // @todo
            passwordMediumBg: 'var(#ffcf91, var(#ff9f42))', // @todo
            passwordStrongBg: 'var(#93deac, var(#29c76f))', // @todo
            buttonPadding: 'var(.75rem 1.25rem, var(.75rem 1.25rem))',
            buttonIconOnlyWidth: 'var(3rem, var(3rem))',
            buttonIconOnlyPadding: 'var(.75rem 0, var(.75rem 0))',
            buttonBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            buttonTextColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            buttonBorder: 'var(1px solid var(--p-dark-primary-color), var(1px solid var(--p-primary-color)))',
            buttonHoverBg: 'var(var(--p-dark-primary-light-color), var(var(--p-primary-dark-color)))',
            buttonTextHoverColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            buttonHoverBorderColor: 'var(var(--p-dark-primary-light-color), var(var(--p-primary-dark-color)))',
            buttonActiveBg: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            buttonTextActiveColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            buttonActiveBorderColor: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            raisedButtonShadow: 'var(0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12), var(0 3px 1px -2px rgba(0,0,0,.2), 0 2px 2px 0 rgba(0,0,0,.14), 0 1px 5px 0 rgba(0,0,0,.12)))',
            roundedButtonBorderRadius: 'var(2rem, var(2rem))',
            textButtonHoverBgOpacity: 'var(.04, var(.04))',
            textButtonActiveBgOpacity: 'var(.16, var(.16))',
            outlinedButtonBorder: 'var(1px solid, var(1px solid))',
            plainButtonTextColor: 'var(var(--p-dark-text-secondary-color), var(var(--p-text-secondary-color)))',
            plainButtonHoverBgColor: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            plainButtonActiveBgColor: 'var(rgba(255,255,255,.16), var(var(--p-shade-300)))',
            secondaryButtonBg: 'var(#94a3b8, var(#64748B))',
            secondaryButtonTextColor: 'var(#020617, var(#ffffff))',
            secondaryButtonBorder: 'var(1px solid #94a3b8, var(1px solid #64748B))',
            secondaryButtonHoverBg: 'var(#cbd5e1, var(#475569))',
            secondaryButtonTextHoverColor: 'var(var(--p-dark-secondary-button-text-color), var(var(--p-secondary-button-text-color)))',
            secondaryButtonHoverBorderColor: 'var(#cbd5e1, var(#475569))',
            secondaryButtonActiveBg: 'var(#e2e8f0, var(#334155))',
            secondaryButtonTextActiveColor: 'var(var(--p-dark-secondary-button-text-color), var(var(--p-secondary-button-text-color)))',
            secondaryButtonActiveBorderColor: 'var(#e2e8f0, var(#334155))',
            secondaryButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-secondary-button-bg), lightness: 30%), var(0 0 0 0.2rem #E2E8F0))',
            infoButtonBg: 'var(#38bdf8, var(#0ea5e9))',
            infoButtonTextColor: 'var(#082f49, var(#ffffff))',
            infoButtonBorder: 'var(1px solid #38bdf8, var(1px solid #0ea5e9))',
            infoButtonHoverBg: 'var(#7dd3fc, var(#0284c7))',
            infoButtonTextHoverColor: 'var(var(--p-dark-info-button-text-color), var(var(--p-info-button-text-color)))',
            infoButtonHoverBorderColor: 'var(#7dd3fc, var(#0284c7))',
            infoButtonActiveBg: 'var(#bae6fd, var(#0369a1))',
            infoButtonTextActiveColor: 'var(var(--p-dark-info-button-text-color), var(var(--p-info-button-text-color)))',
            infoButtonActiveBorderColor: 'var(#bae6fd, var(#0369a1))',
            infoButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-info-button-bg), lightness: 30%), var(0 0 0 0.2rem #BFDBFE))',
            successButtonBg: 'var(#4ade80, var(#22C55E))',
            successButtonTextColor: 'var(#052e16, var(#ffffff))',
            successButtonBorder: 'var(1px solid #4ade80, var(1px solid #22C55E))',
            successButtonHoverBg: 'var(#86efac, var(#16A34A))',
            successButtonTextHoverColor: 'var(var(--p-dark-success-button-text-color), var(var(--p-success-button-text-color)))',
            successButtonHoverBorderColor: 'var(#86efac, var(#16A34A))',
            successButtonActiveBg: 'var(#bbf7d0, var(#15803D))',
            successButtonTextActiveColor: 'var(var(--p-dark-success-button-text-color), var(var(--p-success-button-text-color)))',
            successButtonActiveBorderColor: 'var(#bbf7d0, var(#15803D))',
            successButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-success-button-bg), lightness: 30%), var(0 0 0 0.2rem #BBF7D0))',
            warningButtonBg: 'var(#fb923c, var(#f97316))',
            warningButtonTextColor: 'var(#431407, var(#ffffff))',
            warningButtonBorder: 'var(1px solid #fb923c, var(1px solid #f97316))',
            warningButtonHoverBg: 'var(#fdba74, var(#ea580c))',
            warningButtonTextHoverColor: 'var(var(--p-dark-warning-button-text-color), var(var(--p-warning-button-text-color)))',
            warningButtonHoverBorderColor: 'var(#fdba74, var(#ea580c))',
            warningButtonActiveBg: 'var(#fed7aa, var(#c2410c))',
            warningButtonTextActiveColor: 'var(var(--p-dark-warning-button-text-color), var(var(--p-warning-button-text-color)))',
            warningButtonActiveBorderColor: 'var(#fed7aa, var(#c2410c))',
            warningButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-warning-button-bg), lightness: 30%), var(0 0 0 0.2rem #FDE68A))',
            helpButtonBg: 'var(#c084fc, var(#A855F7))',
            helpButtonTextColor: 'var(#3b0764, var(#ffffff))',
            helpButtonBorder: 'var(1px solid #c084fc, var(1px solid #A855F7))',
            helpButtonHoverBg: 'var(#d8b4fe, var(#9333EA))',
            helpButtonTextHoverColor: 'var(var(--p-dark-help-button-text-color), var(var(--p-help-button-text-color)))',
            helpButtonHoverBorderColor: 'var(#d8b4fe, var(#9333EA))',
            helpButtonActiveBg: 'var(#e9d5ff, var(#7E22CE))',
            helpButtonTextActiveColor: 'var(var(--p-dark-help-button-text-color), var(var(--p-help-button-text-color)))',
            helpButtonActiveBorderColor: 'var(#e9d5ff, var(#7E22CE))',
            helpButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-help-button-bg), lightness: 30%), var(0 0 0 0.2rem #E9D5FF))',
            dangerButtonBg: 'var(#f87171, var(#EF4444))',
            dangerButtonTextColor: 'var(#450a0a, var(#ffffff))',
            dangerButtonBorder: 'var(1px solid #f87171, var(1px solid var(--p-danger-button-bg)))',
            dangerButtonHoverBg: 'var(#fca5a5, var(#DC2626))',
            dangerButtonTextHoverColor: 'var(var(--p-dark-danger-button-text-color), var(var(--p-danger-button-text-color)))',
            dangerButtonHoverBorderColor: 'var(#fca5a5, var(#DC2626))',
            dangerButtonActiveBg: 'var(#fecaca, var(#B91C1C))',
            dangerButtonTextActiveColor: 'var(var(--p-dark-danger-button-text-color), var(var(--p-danger-button-text-color)))',
            dangerButtonActiveBorderColor: 'var(#fecaca, var(#B91C1C))',
            dangerButtonFocusShadow: 'var(0 0 0 1px scale-color(var(--p-dark-danger-button-bg), lightness: 30%), var(0 0 0 0.2rem #FECACA))',
            linkButtonColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-darker-color)))',
            linkButtonHoverColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-darker-color)))',
            linkButtonTextHoverDecoration: 'var(underline, var(underline))',
            linkButtonFocusShadow: 'var(0 0 0 1px var(--p-dark-focus-outline-color), var(0 0 0 0.2rem var(--p-focus-outline-color)))',
            checkboxWidth: 'var(22px, var(22px))',
            checkboxHeight: 'var(22px, var(22px))',
            checkboxBorder: 'var(2px solid var(--p-dark-shade-600), var(2px solid var(--p-shade-400)))',
            checkboxIconFontSize: 'var(14px, var(14px))',
            checkboxActiveBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            checkboxActiveBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            checkboxIconActiveColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            checkboxActiveHoverBg: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            checkboxIconActiveHoverColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            checkboxActiveHoverBorderColor: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            radiobuttonWidth: 'var(22px, var(22px))',
            radiobuttonHeight: 'var(22px, var(22px))',
            radiobuttonBorder: 'var(2px solid var(--p-dark-shade-600), var(2px solid var(--p-shade-400)))',
            radiobuttonIconSize: 'var(12px, var(12px))',
            radiobuttonActiveBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            radiobuttonActiveBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            radiobuttonIconActiveColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            radiobuttonActiveHoverBg: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            radiobuttonIconActiveHoverColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            radiobuttonActiveHoverBorderColor: 'var(var(--p-dark-primary-lighter-color), var(var(--p-primary-darker-color)))',
            colorPickerPreviewWidth: 'var(2rem, var(2rem))',
            colorPickerPreviewHeight: 'var(2rem, var(2rem))',
            colorPickerBg: 'var(var(--p-dark-shade-800), var(#323232))',
            colorPickerBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid #191919))',
            colorPickerHandleColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-0)))',
            toggleButtonBg: 'var(var(--p-dark-shade-800), var(var(--p-input-bg)))',
            toggleButtonBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-400)))',
            toggleButtonTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            toggleButtonIconColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            toggleButtonHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            toggleButtonHoverBorderColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-400)))',
            toggleButtonTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            toggleButtonIconHoverColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-800)))',
            toggleButtonActiveBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            toggleButtonActiveBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            toggleButtonTextActiveColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            toggleButtonIconActiveColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            toggleButtonActiveHoverBg: 'var(var(--p-dark-primary-light-color), var(var(--p-primary-dark-color)))',
            toggleButtonActiveHoverBorderColor: 'var(var(--p-dark-primary-light-color), var(var(--p-primary-dark-color)))',
            toggleButtonTextActiveHoverColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            toggleButtonIconActiveHoverColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            inplacePadding: 'var(var(--p-dark-input-padding), var(var(--p-input-padding)))',
            inplaceHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            inplaceTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            ratingIconFontSize: 'var(1.143rem, var(1.143rem))',
            ratingCancelIconColor: 'var(#F48FB1, var(#ea5455))',
            ratingCancelIconHoverColor: 'var(#F48FB1, var(#e73d3e))',
            ratingStarIconOffColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            ratingStarIconOnColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            ratingStarIconHoverColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            sliderBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            sliderBorder: 'var(0 none, var(0 none))',
            sliderHorizontalHeight: 'var(.286rem, var(.286rem))',
            sliderVerticalWidth: 'var(0.286rem, var(0.286rem))',
            sliderHandleWidth: 'var(1.143rem, var(1.143rem))',
            sliderHandleHeight: 'var(1.143rem, var(1.143rem))',
            sliderHandleBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-0)))',
            sliderHandleBorder: 'var(2px solid var(--p-dark-primary-color), var(2px solid var(--p-primary-color)))',
            sliderHandleBorderRadius: 'var(50%, var(50%))',
            sliderHandleHoverBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            sliderHandleHoverBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            sliderRangeBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            calendarTableMargin: 'var(.5rem 0, var(.5rem 0))',
            calendarPadding: 'var(.5rem, var(.5rem))',
            calendarBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            calendarInlineBg: 'var(var(--p-dark-calendar-bg), var(var(--p-calendar-bg)))',
            calendarTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            calendarBorder: 'var(var(--p-dark-input-list-border), var(var(--p-input-list-border)))',
            calendarOverlayBorder: 'var(var(--p-dark-input-overlay-border), var(var(--p-input-overlay-border)))',
            calendarHeaderPadding: 'var(.5rem, var(.5rem))',
            calendarHeaderBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            calendarInlineHeaderBg: 'var(var(--p-dark-calendar-bg), var(var(--p-calendar-bg)))',
            calendarHeaderBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            calendarHeaderTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            calendarHeaderFontWeight: 'var(700, var(600))',
            calendarHeaderCellPadding: 'var(.5rem, var(.5rem))',
            calendarMonthYearHeaderHoverTextColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            calendarCellDatePadding: 'var(.5rem, var(.5rem))',
            calendarCellDateWidth: 'var(2.5rem, var(2.5rem))',
            calendarCellDateHeight: 'var(2.5rem, var(2.5rem))',
            calendarCellDateBorderRadius: 'var(50%, var(50%))',
            calendarCellDateBorder: 'var(1px solid transparent, var(1px solid transparent))',
            calendarCellDateHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            calendarCellDateTodayBg: 'var(transparent, var(var(--p-shade-400)))',
            calendarCellDateTodayBorderColor: 'var(transparent, var(transparent))',
            calendarCellDateTodayTextColor: 'var(var(--p-dark-primary-color), var(var(--p-shade-700)))',
            calendarButtonBarPadding: 'var(1rem 0, var(1rem 0))',
            calendarTimePickerPadding: 'var(.5rem, var(.5rem))',
            calendarTimePickerElementPadding: 'var(0 .5rem, var(0 .5rem))',
            calendarTimePickerTimeFontSize: 'var(1.25rem, var(1.25rem))',
            calendarBreakpoint: 'var(769px, var(769px))',
            calendarCellDatePaddingSM: 'var(0, var(0))',
            inputSwitchWidth: 'var(3rem, var(3rem))',
            inputSwitchHeight: 'var(1.75rem, var(1.75rem))',
            inputSwitchBorderRadius: 'var(30px, var(30px))',
            inputSwitchHandleWidth: 'var(1.250rem, var(1.250rem))',
            inputSwitchHandleHeight: 'var(1.250rem, var(1.250rem))',
            inputSwitchHandleBorderRadius: 'var(50%, var(50%))',
            inputSwitchSliderPadding: 'var(.25rem, var(.25rem))',
            inputSwitchSliderOffBg: 'var(var(--p-dark-shade-500), var(var(--p-shade-400)))',
            inputSwitchHandleOffBg: 'var(var(--p-dark-shade-100), var(var(--p-shade-0)))',
            inputSwitchSliderOffHoverBg: 'var(var(--p-dark-shade-600), var(#b7bcc5))',
            inputSwitchSliderOnBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            inputSwitchSliderOnHoverBg: 'var(var(--p-dark-primary-light-color), var(var(--p-primary-dark-color)))',
            inputSwitchHandleOnBg: 'var(var(--p-dark-primary-text-color), var(var(--p-shade-0)))',
            panelHeaderBorderColor: 'var(--p-dark-shade-600, var(--p-shade-300))',
            panelHeaderBorder: '1px solid var(--p-dark-shade-600, var(--p-shade-300))',
            panelHeaderBg: 'var(--p-dark-shade-800, var(--p-shade-100))',
            panelHeaderTextColor: 'var(--p-dark-shade-0, var(--p-shade-800))',
            panelHeaderFontWeight: '700',
            panelHeaderPadding: '1.25rem',
            panelToggleableHeaderPadding: '.75rem 1.25rem',
            panelHeaderHoverBg: 'var(--p-dark-hover-bg, var(--p-shade-200))',
            panelHeaderHoverBorderColor: 'var(--p-dark-shade-600, var(--p-shade-300))',
            panelHeaderTextHoverColor: 'var(--p-dark-shade-0, var(--p-shade-800))',
            panelContentBorderColor: 'var(--p-dark-shade-600, var(--p-shade-300))',
            panelContentBorder: '1px solid var(--p-dark-shade-600, var(--p-shade-300))',
            panelContentBg: 'var(--p-dark-shade-800, var(--p-shade-0))',
            panelContentEvenRowBg: 'var(#1c2532, var(#f8f8fa))', // @todo
            panelContentTextColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            panelContentPadding: '1.25rem',
            panelFooterBorder: '1px solid var(--p-dark-shade-600, var(--p-shade-300))',
            panelFooterBg: 'var(--p-dark-shade-800, var(--p-shade-0))',
            panelFooterTextColor: 'var(--p-dark-shade-0, var(--p-shade-700))',
            panelFooterPadding: '0.75rem 1.25rem',
            accordionSpacing: 'var(4px, var(4px))',
            accordionHeaderBorder: 'var(var(--p-dark-panel-header-border), var(var(--p-panel-header-border)))',
            accordionHeaderBg: 'var(var(--p-dark-panel-header-bg), var(var(--p-panel-header-bg)))',
            accordionHeaderTextColor: 'var(var(--p-dark-panel-header-text-color), var(var(--p-shade-600)))',
            accordionHeaderFontWeight: 'var(var(--p-dark-panel-header-font-weight), var(var(--p-panel-header-font-weight)))',
            accordionHeaderPadding: 'var(var(--p-dark-panel-header-padding), var(var(--p-panel-header-padding)))',
            accordionHeaderHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            accordionHeaderHoverBorderColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            accordionHeaderTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            accordionHeaderActiveBg: 'var(var(--p-dark-panel-header-bg), var(var(--p-panel-header-bg)))',
            accordionHeaderActiveBorderColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            accordionHeaderTextActiveColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            accordionHeaderActiveHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            accordionHeaderActiveHoverBorderColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            accordionHeaderTextActiveHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            accordionContentBorder: 'var(var(--p-dark-panel-content-border), var(var(--p-panel-content-border)))',
            accordionContentBg: 'var(var(--p-dark-panel-content-bg), var(var(--p-panel-content-bg)))',
            accordionContentTextColor: 'var(var(--p-dark-panel-content-text-color), var(var(--p-panel-content-text-color)))',
            accordionContentPadding: 'var(var(--p-dark-panel-content-padding), var(var(--p-panel-content-padding)))',
            tabviewNavBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tabviewNavBorderWidth: 'var(0 0 2px 0, var(0 0 2px 0))',
            tabviewNavBg: 'var(transparent, var(var(--p-shade-0)))',
            tabviewHeaderSpacing: 'var(0, var(0))',
            tabviewHeaderBorder: 'var(solid var(--p-dark-shade-600), var(solid var(--p-shade-300)))',
            tabviewHeaderBorderWidth: 'var(0 0 2px 0, var(0 0 2px 0))',
            tabviewHeaderBorderColor: 'var(transparent transparent var(--p-dark-shade-600) transparent, var(transparent transparent var(--p-shade-300) transparent))',
            tabviewHeaderBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            tabviewHeaderTextColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            tabviewHeaderFontWeight: 'var(var(--p-dark-panel-header-font-weight), var(var(--p-panel-header-font-weight)))',
            tabviewHeaderPadding: 'var(var(--p-dark-panel-header-padding), var(var(--p-panel-header-padding)))',
            tabviewHeaderMargin: 'var(0 0 -2px 0, var(0 0 -2px 0))',
            tabviewHeaderHoverBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            tabviewHeaderHoverBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-shade-500)))',
            tabviewHeaderTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-600)))',
            tabviewHeaderActiveBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            tabviewHeaderActiveBorderColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            tabviewHeaderTextActiveColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            tabviewContentBorder: 'var(0 none, var(0 none))',
            tabviewContentBg: 'var(var(--p-dark-shade-800), var(var(--p-panel-content-bg)))',
            tabviewContentTextColor: 'var(var(--p-dark-shade-0), var(var(--p-panel-content-text-color)))',
            tabviewContentPadding: 'var(var(--p-dark-panel-content-padding), var(var(--p-panel-content-padding)))',
            fileUploadProgressBarHeight: 'var(.25rem, var(.25rem))',
            fileUploadContentPadding: 'var(2rem 1rem, var(2rem 1rem))',
            fileUploadContentHoverBorder: 'var(1px dashed var(--p-dark-primary-color), var(1px dashed var(--p-primary-color)))',
            fileUploadFileBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            fileUploadFilePadding: 'var(1rem, var(1rem))',
            scrollPanelTrackBorder: 'var(0 none, var(0 none))',
            scrollPanelTrackBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-100)))',
            cardBodyPadding: 'var(1.25rem, var(1.25rem))',
            cardTitleFontSize: 'var(1.5rem, var(1.5rem))',
            cardTitleFontWeight: 'var(700, var(700))',
            cardSubTitleFontWeight: 'var(400, var(400))',
            cardSubTitleColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            cardContentPadding: 'var(1.25rem 0, var(1.25rem 0))',
            cardFooterPadding: 'var(1.25rem 0 0 0, var(1.25rem 0 0 0))',
            cardShadow: 'var(0 2px 1px -1px rgba(0,0,0,.2), 0 1px 1px 0 rgba(0,0,0,.14), 0 1px 3px 0 rgba(0,0,0,.12), var(0 2px 1px -1px rgba(0,0,0,.2), 0 1px 1px 0 rgba(0,0,0,.14), 0 1px 3px 0 rgba(0,0,0,.12)))',
            editorToolbarBg: 'var(var(--p-dark-panel-header-bg), var(var(--p-panel-header-bg)))',
            editorToolbarBorder: 'var(var(--p-dark-panel-header-border), var(var(--p-panel-header-border)))',
            editorToolbarPadding: 'var(var(--p-dark-panel-header-padding), var(var(--p-panel-header-padding)))',
            editorToolbarIconColor: 'var(var(--p-dark-text-secondary-color), var(var(--p-text-secondary-color)))',
            editorToolbarIconHoverColor: 'var(var(--p-dark-text-color), var(var(--p-text-color)))',
            editorIconActiveColor: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            editorContentBorder: 'var(var(--p-dark-panel-content-border), var(var(--p-panel-content-border)))',
            editorContentBg: 'var(var(--p-dark-panel-content-bg), var(var(--p-panel-content-bg)))',
            paginatorBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            paginatorTextColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            paginatorBorder: 'var(solid var(--p-dark-shade-600), var(solid var(--p-shade-200)))',
            paginatorBorderWidth: 'var(1px, var(0))',
            paginatorPadding: 'var(.5rem 1rem, var(.5rem 1rem))',
            paginatorElementWidth: 'var(var(--p-dark-button-icon-only-width), var(var(--p-button-icon-only-width)))',
            paginatorElementHeight: 'var(var(--p-dark-button-icon-only-width), var(var(--p-button-icon-only-width)))',
            paginatorElementBg: 'var(transparent, var(transparent))',
            paginatorElementBorder: 'var(0 none, var(0 none))',
            paginatorElementIconColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            paginatorElementHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            paginatorElementHoverBorderColor: 'var(transparent, var(transparent))',
            paginatorElementIconHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            paginatorElementBorderRadius: 'var(var(--p-dark-border-radius), var(50%))',
            paginatorElementMargin: 'var(.143rem, var(.143rem))',
            paginatorElementPadding: 'var(0, var(0))',
            tableHeaderBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tableHeaderBorderWidth: 'var(0 0 1px 0, var(1px 0 1px 0))',
            tableHeaderBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-100)))',
            tableHeaderTextColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-800)))',
            tableHeaderFontWeight: 'var(700, var(700))',
            tableHeaderPadding: 'var(1rem 1rem, var(1rem 1rem))',
            tableHeaderCellPadding: 'var(1rem 1rem, var(1rem 1rem))',
            tableHeaderCellBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-100)))',
            tableHeaderCellTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            tableHeaderCellFontWeight: 'var(700, var(700))',
            tableHeaderCellBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tableHeaderCellBorderWidth: 'var(0 0 1px 0, var(0 0 1px 0))',
            tableHeaderCellHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            tableHeaderCellTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            tableHeaderCellIconColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-800)))',
            tableHeaderCellIconHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            tableHeaderCellHighlightBg: 'var(var(--p-dark-highlight-bg), var(var(--p-highlight-bg)))',
            tableHeaderCellHighlightTextColor: 'var(var(--p-dark-highlight-text-color), var(var(--p-highlight-text-color)))',
            tableHeaderCellHighlightHoverBg: 'var(var(--p-dark-highlight-bg), var(var(--p-highlight-bg)))',
            tableHeaderCellHighlightTextHoverColor: 'var(var(--p-dark-highlight-text-color), var(var(--p-highlight-text-color)))',
            tableSortableColumnBadgeSize: 'var(1.143rem, var(1.143rem))',
            tableBodyRowBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            tableBodyRowTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            tableBodyRowEvenBg: 'var(#1c2532, var(#f8f8fa))',
            tableBodyRowHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            tableBodyRowTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            tableBodyCellBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tableBodyCellBorderWidth: 'var(0 0 1px 0, var(0 0 1px 0))',
            tableBodyCellPadding: 'var(1rem 1rem, var(1rem 1rem))',
            tableFooterCellPadding: 'var(1rem 1rem, var(1rem 1rem))',
            tableFooterCellBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-100)))',
            tableFooterCellTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            tableFooterCellFontWeight: 'var(700, var(700))',
            tableFooterCellBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tableFooterCellBorderWidth: 'var(0 0 1px 0, var(0 0 1px 0))',
            tableResizerHelperBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            tableFooterBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            tableFooterBorderWidth: 'var(0 0 1px 0, var(0 0 1px 0))',
            tableFooterBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-100)))',
            tableFooterTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            tableFooterFontWeight: 'var(700, var(700))',
            tableFooterPadding: 'var(1rem 1rem, var(1rem 1rem))',
            tableCellContentAlignment: 'var(left, var(left))',
            tableTopPaginatorBorderWidth: 'var(1px 0 1px 0, var(0 0 1px 0))',
            tableBottomPaginatorBorderWidth: 'var(0 0 1px 0, var(0 0 1px 0))',
            tableScaleSM: 'var(0.5, var(0.5))',
            tableScaleLG: 'var(1.25, var(1.25))',
            dataViewContentPadding: 'var(0, var(0))',
            dataViewContentBorder: 'var(0 none, var(0 none))',
            treeContainerPadding: 'var(0.286rem, var(0.286rem))',
            treeNodePadding: 'var(0.143rem, var(0.143rem))',
            treeNodeContentPadding: 'var(.5rem, var(.5rem))',
            treeNodeChildrenPadding: 'var(0 0 0 1rem, var(0 0 0 1rem))',
            treeNodeIconColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            timelineVerticalEventContentPadding: 'var(0 1rem, var(0 1rem))',
            timelineHorizontalEventContentPadding: 'var(1rem 0, var(1rem 0))',
            timelineEventMarkerWidth: 'var(1rem, var(1rem))',
            timelineEventMarkerHeight: 'var(1rem, var(1rem))',
            timelineEventMarkerBorderRadius: 'var(50%, var(50%))',
            timelineEventMarkerBorder: 'var(2px solid var(--p-dark-primary-color), var(2px solid var(--p-primary-color)))',
            timelineEventMarkerBackground: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            timelineEventConnectorSize: 'var(2px, var(2px))',
            timelineEventColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            organizationChartConnectorColor: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            messageMargin: 'var(1rem 0, var(1rem 0))',
            messagePadding: 'var(1.25rem 1.75rem, var(1.25rem 1.75rem))',
            messageBorderWidth: 'var(0 0 0 6px, var(0 0 0 6px))',
            messageIconFontSize: 'var(1.5rem, var(1.5rem))',
            messageTextFontSize: 'var(1rem, var(1rem))',
            messageTextFontWeight: 'var(500, var(500))',
            inlineMessagePadding: 'var(var(--p-dark-input-padding), var(var(--p-input-padding)))',
            inlineMessageMargin: 'var(0, var(0))',
            inlineMessageIconFontSize: 'var(1rem, var(1rem))',
            inlineMessageTextFontSize: 'var(1rem, var(1rem))',
            inlineMessageBorderWidth: 'var(1px, var(0px))',
            toastIconFontSize: 'var(2rem, var(2rem))',
            toastMessageTextMargin: 'var(0 0 0 1rem, var(0 0 0 1rem))',
            toastMargin: 'var(0 0 1rem 0, var(0 0 1rem 0))',
            toastPadding: 'var(1rem, var(1rem))',
            toastBorderWidth: 'var(0 0 0 6px, var(0 0 0 6px))',
            toastShadow: 'var(none, var(0 2px 12px 0 rgba(0,0,0,.1)))',
            toastOpacity: 'var(1, var(1))',
            toastTitleFontWeight: 'var(700, var(700))',
            toastDetailMargin: 'var(var(--p-dark-inline-spacing) 0 0 0, var(var(--p-inline-spacing) 0 0 0))',
            infoMessageBg: 'var(rgba(59,130,246,.2), var(rgba(219, 234, 254, .7)))',
            infoMessageBorder: 'var(solid #3b82f6, var(solid #3b82f6))',
            infoMessageTextColor: 'var(#93c5fd, var(#3b82f6))',
            infoMessageIconColor: 'var(#93c5fd, var(#3b82f6))',
            successMessageBg: 'var(rgba(16, 185, 129, .2), var(rgba(228, 248, 240, .7)))',
            successMessageBorder: 'var(solid #10b981, var(solid #1ea97c))',
            successMessageTextColor: 'var(#6ee7b7, var(#1ea97c))',
            successMessageIconColor: 'var(#6ee7b7, var(#1ea97c))',
            warningMessageBg: 'var(rgba(234, 179, 8, .2), var(rgba(255, 242, 226, .7)))',
            warningMessageBorder: 'var(solid #eab308, var(solid #cc8925))',
            warningMessageTextColor: 'var(#fde047, var(#cc8925))',
            warningMessageIconColor: 'var(#fde047, var(#cc8925))',
            errorMessageBg: 'var(rgba(239, 68, 68, .2), var(rgba(255, 231, 230, .7)))',
            errorMessageBorder: 'var(solid #ef4444, var(solid #ff5757))',
            errorMessageTextColor: 'var(#fca5a5, var(#ff5757))',
            errorMessageIconColor: 'var(#fca5a5, var(#ff5757))',
            overlayContentBorder: 'var(1px solid var(--p-dark-shade-600), var(0 none))',
            overlayContentBg: 'var(var(--p-dark-panel-content-bg), var(var(--p-panel-content-bg)))',
            overlayContainerShadow: 'var(0px 11px 15px -7px rgba(0, 0, 0, 0.2), 0px 24px 38px 3px rgba(0, 0, 0, 0.14), 0px 9px 46px 8px rgba(0,0,0,.12), var(0 1px 3px rgba(0,0,0,.3)))',
            dialogHeaderBg: 'var(var(--p-dark-shade-800), var(var(--p-shade-0)))',
            dialogHeaderBorder: 'var(0 none, var(0 none))',
            dialogHeaderTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            dialogHeaderFontWeight: 'var(700, var(700))',
            dialogHeaderFontSize: 'var(1.25rem, var(1.25rem))',
            dialogHeaderPadding: 'var(1.5rem, var(1.5rem))',
            dialogContentPadding: 'var(0 1.5rem 2rem 1.5rem, var(0 1.5rem 2rem 1.5rem))',
            dialogFooterBorder: 'var(0 none, var(0 none))',
            dialogFooterPadding: 'var(0 1.5rem 1.5rem 1.5rem, var(0 1.5rem 1.5rem 1.5rem))',
            confirmPopupContentPadding: 'var(var(--p-dark-panel-content-padding), var(var(--p-panel-content-padding)))',
            confirmPopupFooterPadding: 'var(0 1.25rem 1.25rem 1.25rem, var(0 1.25rem 1.25rem 1.25rem))',
            tooltipBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-700)))',
            tooltipTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-0)))',
            tooltipPadding: 'var(var(--p-dark-input-padding), var(var(--p-input-padding)))',
            stepsItemBg: 'var(transparent, var(var(--p-shade-0)))',
            stepsItemBorder: 'var(0 none, var(1px solid var(--p-shade-200)))',
            stepsItemTextColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            stepsItemNumberWidth: 'var(2rem, var(2rem))',
            stepsItemNumberHeight: 'var(2rem, var(2rem))',
            stepsItemNumberFontSize: 'var(1.143rem, var(1.143rem))',
            stepsItemNumberColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            stepsItemNumberBorderRadius: 'var(50%, var(50%))',
            stepsItemActiveFontWeight: 'var(700, var(700))',
            progressBarHeight: 'var(1.5rem, var(1.5rem))',
            progressBarBorder: 'var(0 none, var(0 none))',
            progressBarBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            progressBarValueBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            progressBarValueTextColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            progressSpinnerStrokeColor: 'var(var(--p-dark-error-message-text-color), var(var(--p-error-message-text-color)))',
            progressSpinnerColorOne: 'var(var(--p-dark-error-message-text-color), var(var(--p-error-message-text-color)))',
            progressSpinnerColorTwo: 'var(var(--p-dark-info-message-text-color), var(var(--p-info-message-text-color)))',
            progressSpinnerColorThree: 'var(var(--p-dark-success-message-text-color), var(var(--p-success-message-text-color)))',
            progressSpinnerColorFour: 'var(var(--p-dark-warning-message-text-color), var(var(--p-warning-message-text-color)))',
            menuWidth: 'var(12.5rem, var(12.5rem))',
            menuBg: 'var(var(--p-dark-shade-700), var(var(--p-shade-0)))',
            menuBorder: 'var(1px solid var(--p-dark-shade-600), var(1px solid var(--p-shade-300)))',
            menuTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            menuitemPadding: 'var(.75rem 1.25rem, var(.75rem 1.25rem))',
            menuitemBorderRadius: 'var(0, var(0))',
            menuitemTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            menuitemIconColor: 'var(var(--p-dark-shade-100), var(var(--p-shade-600)))',
            menuitemTextHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            menuitemIconHoverColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-600)))',
            menuitemHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-200)))',
            menuitemTextFocusColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            menuitemIconFocusColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-700)))',
            menuitemFocusBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-300)))',
            menuitemTextActiveColor: 'var(var(--p-dark-highlight-text-color), var(var(--p-highlight-text-color)))',
            menuitemIconActiveColor: 'var(var(--p-dark-highlight-text-color), var(var(--p-highlight-text-color)))',
            menuitemActiveBg: 'var(var(--p-dark-highlight-bg), var(var(--p-highlight-bg)))',
            menuitemActiveFocusBg: 'var(var(--p-dark-highlight-focus-bg), var(var(--p-highlight-focus-bg)))',
            menuitemSubmenuIconFontSize: 'var(.875rem, var(.875rem))',
            submenuHeaderMargin: 'var(0, var(0))',
            submenuHeaderPadding: 'var(.75rem 1.25rem, var(.75rem 1.25rem))',
            submenuHeaderBg: 'var(var(--p-dark-shade-700), var(var(--p-shade-0)))',
            submenuHeaderTextColor: 'var(var(--p-dark-shade-0), var(var(--p-shade-800)))',
            submenuHeaderBorderRadius: 'var(0, var(0))',
            submenuHeaderFontWeight: 'var(700, var(700))',
            overlayMenuBg: 'var(var(--p-dark-menu-bg), var(var(--p-menu-bg)))',
            overlayMenuBorder: 'var(1px solid var(--p-dark-shade-600), var(0 none))',
            overlayMenuShadow: 'var(0 2px 4px -1px rgba(0,0,0,.2), 0 4px 5px 0 rgba(0,0,0,.14), 0 1px 10px 0 rgba(0,0,0,.12), var(0 2px 12px 0 rgba(0,0,0,.1)))',
            verticalMenuPadding: 'var(.25rem 0, var(.5rem 0))',
            menuSeparatorMargin: 'var(.25rem 0, var(.25rem 0))',
            breadcrumbPadding: 'var(1rem, var(1rem))',
            breadcrumbBg: 'var(var(--p-dark-menu-bg), var(var(--p-menu-bg)))',
            breadcrumbBorder: 'var(var(--p-dark-menu-border), var(var(--p-menu-border)))',
            breadcrumbItemTextColor: 'var(var(--p-dark-menuitem-text-color), var(var(--p-menuitem-text-color)))',
            breadcrumbItemIconColor: 'var(var(--p-dark-menuitem-icon-color), var(var(--p-menuitem-icon-color)))',
            breadcrumbLastItemTextColor: 'var(var(--p-dark-menuitem-text-color), var(var(--p-menuitem-text-color)))',
            breadcrumbLastItemIconColor: 'var(var(--p-dark-menuitem-icon-color), var(var(--p-menuitem-icon-color)))',
            breadcrumbSeparatorColor: 'var(var(--p-dark-menuitem-text-color), var(var(--p-menuitem-text-color)))',
            horizontalMenuPadding: 'var(.5rem, var(.5rem))',
            horizontalMenuBg: 'var(var(--p-dark-shade-700), var(var(--p-shade-100)))',
            horizontalMenuBorder: 'var(var(--p-dark-menu-border), var(var(--p-menu-border)))',
            horizontalMenuTextColor: 'var(var(--p-dark-menu-text-color), var(var(--p-menu-text-color)))',
            horizontalMenuRootMenuitemPadding: 'var(var(--p-dark-menuitem-padding), var(var(--p-menuitem-padding)))',
            horizontalMenuRootMenuitemBorderRadius: 'var(var(--p-dark-border-radius), var(var(--p-border-radius)))',
            horizontalMenuRootMenuitemTextColor: 'var(var(--p-dark-menuitem-text-color), var(var(--p-menuitem-text-color)))',
            horizontalMenuRootMenuitemIconColor: 'var(var(--p-dark-menuitem-icon-color), var(var(--p-menuitem-icon-color)))',
            horizontalMenuRootMenuitemTextHoverColor: 'var(var(--p-dark-menuitem-text-hover-color), var(var(--p-menuitem-text-hover-color)))',
            horizontalMenuRootMenuitemIconHoverColor: 'var(var(--p-dark-menuitem-icon-hover-color), var(var(--p-menuitem-icon-hover-color)))',
            horizontalMenuRootMenuitemHoverBg: 'var(var(--p-dark-menuitem-hover-bg), var(var(--p-menuitem-hover-bg)))',
            horizontalMenuRootMenuitemTextActiveColor: 'var(var(--p-dark-menuitem-text-active-color), var(var(--p-menuitem-text-active-color)))',
            horizontalMenuRootMenuitemIconActiveColor: 'var(var(--p-dark-menuitem-icon-active-color), var(var(--p-menuitem-icon-active-color)))',
            horizontalMenuRootMenuitemActiveBg: 'var(var(--p-dark-menuitem-active-bg), var(var(--p-menuitem-active-bg)))',
            badgeBg: 'var(var(--p-dark-primary-color), var(var(--p-primary-color)))',
            badgeTextColor: 'var(var(--p-dark-primary-text-color), var(var(--p-primary-text-color)))',
            badgeMinWidth: 'var(1.5rem, var(1.5rem))',
            badgeHeight: 'var(1.5rem, var(1.5rem))',
            badgeFontWeight: 'var(700, var(700))',
            badgeFontSize: 'var(.75rem, var(.75rem))',
            tagPadding: 'var(.25rem .4rem, var(.25rem .4rem))',
            carouselIndicatorsPadding: 'var(1rem, var(1rem))',
            carouselIndicatorBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-400)))',
            carouselIndicatorHoverBg: 'var(var(--p-dark-hover-bg), var(var(--p-shade-500)))',
            carouselIndicatorBorderRadius: 'var(0, var(0))',
            carouselIndicatorWidth: 'var(2rem, var(2rem))',
            carouselIndicatorHeight: 'var(.5rem, var(.5rem))',
            galleriaMaskBg: 'var(rgba(0,0,0,0.9), var(rgba(0,0,0,0.9)))',
            galleriaCloseIconMargin: 'var(.5rem, var(.5rem))',
            galleriaCloseIconFontSize: 'var(2rem, var(2rem))',
            galleriaCloseIconBg: 'var(transparent, var(transparent))',
            galleriaCloseIconColor: 'var(#f8f9fa, var(var(--p-shade-100)))',
            galleriaCloseIconHoverBg: 'var(rgba(255,255,255,0.1), var(rgba(255,255,255,0.1)))',
            galleriaCloseIconHoverColor: 'var(#f8f9fa, var(var(--p-shade-100)))',
            galleriaCloseIconWidth: 'var(4rem, var(4rem))',
            galleriaCloseIconHeight: 'var(4rem, var(4rem))',
            galleriaCloseIconBorderRadius: 'var(50%, var(50%))',
            galleriaItemNavigatorBg: 'var(transparent, var(transparent))',
            galleriaItemNavigatorColor: 'var(#f8f9fa, var(var(--p-shade-100)))',
            galleriaItemNavigatorMargin: 'var(0 .5rem, var(0 .5rem))',
            galleriaItemNavigatorFontSize: 'var(2rem, var(2rem))',
            galleriaItemNavigatorHoverBg: 'var(rgba(255,255,255,0.1), var(rgba(255,255,255,0.1)))',
            galleriaItemNavigatorHoverColor: 'var(#f8f9fa, var(var(--p-shade-100)))',
            galleriaItemNavigatorWidth: 'var(4rem, var(4rem))',
            galleriaItemNavigatorHeight: 'var(4rem, var(4rem))',
            galleriaItemNavigatorBorderRadius: 'var(var(--p-dark-border-radius), var(var(--p-border-radius)))',
            galleriaCaptionBg: 'var(rgba(0,0,0,.5), var(rgba(0,0,0,.5)))',
            galleriaCaptionTextColor: 'var(#f8f9fa, var(var(--p-shade-100)))',
            galleriaCaptionPadding: 'var(1rem, var(1rem))',
            galleriaIndicatorsPadding: 'var(1rem, var(1rem))',
            galleriaIndicatorBg: 'var(var(--p-dark-shade-600), var(var(--p-shade-400)))',
            galleriaIndicatorHoverBg: 'var(rgba(255,255,255,0.1), var(var(--p-shade-500)))',
            galleriaIndicatorBorderRadius: 'var(50%, var(50%))',
            galleriaIndicatorWidth: 'var(1rem, var(1rem))',
            galleriaIndicatorHeight: 'var(1rem, var(1rem))',
            galleriaIndicatorsBgOnItem: 'var(rgba(0,0,0,.5), var(rgba(0,0,0,.5)))',
            galleriaIndicatorBgOnItem: 'var(rgba(255,255,255,.4), var(rgba(255,255,255,.4)))',
            galleriaIndicatorHoverBgOnItem: 'var(rgba(255,255,255,.6), var(rgba(255,255,255,.6)))',
            galleriaThumbnailContainerBg: 'rgba(0,0,0,.9)',
            galleriaThumbnailContainerPadding: '1rem .25rem',
            galleriaThumbnailNavigatorBg: 'transparent',
            galleriaThumbnailNavigatorColor: 'var(#f8f9fa, var(var(--p-shade-100)))', //@todo
            galleriaThumbnailNavigatorHoverBg: 'rgba(255,255,255,0.1)',
            galleriaThumbnailNavigatorHoverColor: 'var(#f8f9fa, var(var(--p-shade-100)))', // @todo
            galleriaThumbnailNavigatorBorderRadius: '50%',
            galleriaThumbnailNavigatorWidth: '2rem',
            galleriaThumbnailNavigatorHeight: '2rem',
            dividerHorizontalMargin: '1.25rem 0',
            dividerHorizontalPadding: '0 1.25rem',
            dividerVerticalMargin: '0 1.25rem',
            dividerVerticalPadding: '1.25rem 0',
            dividerSize: '1px',
            dividerColor: 'var(--p-dark-shade-600, var(--p-shade-300))',
            avatarBg: 'var(--p-dark-shade-600, var(--p-shade-300))',
            avatarTextColor: 'var(--p-dark-text-color, var(--p-text-color))',
            chipBg: 'var(--p-dark-shade-600, var(--p-shade-300))',
            chipTextColor: 'var(--p-dark-text-color, var(--p-text-color))',
            chipBorderRadius: '16px',
            chipFocusBg: 'var(--p-dark-shade-500, var(--p-shade-400))',
            chipFocusTextColor: 'var(--p-dark-text-color, var(--p-text-color))',
            scrollTopBg: 'var(--p-dark-highlight-bg, rgba(0,0,0,0.7))',
            scrollTopHoverBg: 'var(scale-color(var(--p-dark-highlight-bg), alpha: 24%), var(rgba(0,0,0,0.8)))', // @todo
            scrollTopWidth: '3rem',
            scrollTopHeight: '3rem',
            scrollTopBorderRadius: '50%',
            scrollTopFontSize: '1.5rem',
            scrollTopTextColor: 'var(--p-dark-highlight-text-color, var(--p-shade-100))',
            skeletonBg: 'var(rgba(255,255,255,.06), var(var(--p-shade-300)))', // @todo
            skeletonAnimationBg: 'rgba(255,255,255,.04)',
            splitterGutterBg: 'var(rgba(255,255,255,.03), var(var(--p-shade-100)))', // @todo
            splitterGutterHandleBg: 'var(--p-dark-shade-600, var(--p-shade-300))',
            speedDialButtonWidth: '4rem',
            speedDialButtonHeight: '4rem',
            speedDialButtonIconFontSize: '1.3rem',
            speedDialActionWidth: '3rem',
            speedDialActionHeight: '3rem',
            speedDialActionBg: 'var(--p-dark-shade-0, var(--p-shade-700))',
            speedDialActionHoverBg: 'var(--p-dark-shade-100, #022354)',
            speedDialActionTextColor: 'var(--p-dark-shade-900, #fff)',
            speedDialActionTextHoverColor: 'var(--p-dark-shade-900, #fff)',
            dockActionWidth: '4rem',
            dockActionHeight: '4rem',
            dockItemPadding: '.5rem',
            dockItemBorderRadius: 'var(--p-dark-border-radius, var(--p-border-radius))',
            dockCurrentItemMargin: '1.5rem',
            dockFirstItemsMargin: '1.3rem',
            dockSecondItemsMargin: '0.9rem',
            dockBg: 'rgba(255,255,255,.1)',
            dockBorder: '1px solid rgba(255,255,255,0.2)',
            dockPadding: '.5rem .5rem',
            dockBorderRadius: '.5rem',
            imageMaskBg: 'rgba(0,0,0,0.9)',
            imagePreviewToolbarPadding: '1rem',
            imagePreviewIndicatorColor: '#f8f9fa',
            imagePreviewIndicatorBg: 'rgba(0,0,0,0.5)',
            imagePreviewActionIconBg: 'transparent',
            imagePreviewActionIconColor: '#f8f9fa',
            imagePreviewActionIconHoverBg: 'rgba(255,255,255,0.1)',
            imagePreviewActionIconHoverColor: '#f8f9fa',
            imagePreviewActionIconWidth: '3rem',
            imagePreviewActionIconHeight: '3rem',
            imagePreviewActionIconFontSize: '1.5rem',
            imagePreviewActionIconBorderRadius: '50%'
        },
        colorScheme: {
            // @todo
            light: {
                primary: palette('#10b981'),
                surface: {
                    a: '#ffffff',
                    b: '#f9fafb',
                    c: '#f3f4f6',
                    d: '#e5e7eb',
                    e: '#ffffff',
                    f: '#ffffff',
                    0: '#ffffff',
                    50: '#f9fafb',
                    100: '#f3f4f6',
                    200: '#e5e7eb',
                    300: '#d1d5db',
                    400: '#9ca3af',
                    500: '#6b7280',
                    600: '#4b5563',
                    700: '#374151',
                    800: '#1f2937',
                    900: '#111827'
                },
                primaryColor: '#10b981',
                primaryLightColor: '#a7f3d0',
                primaryDarkColor: '#059669',
                primaryDarkerColor: '#047857',
                primaryTextColor: '#ffffff',
                highlightBg: '#F0FDFA',
                highlightTextColor: '{primaryDarkerColor}',
                highlightFocusBg: 'color-mix(in srgb, var(--primary-500) 24%, transparent)'
            },
            dark: {
                primary: palette('#34d399'),
                pink: palette('#EC4899'),
                surface: {
                    a: '#1f2937',
                    b: '#111827',
                    c: 'rgba(255,255,255,.03)',
                    d: '#424b57',
                    e: '#1f2937',
                    f: '#1f2937',
                    0: '#111827',
                    50: '#1f2937',
                    100: '#374151',
                    200: '#4b5563',
                    300: '#6b7280',
                    400: '#9ca3af',
                    500: '#d1d5db',
                    600: '#e5e7eb',
                    700: '#f3f4f6',
                    800: '#f9fafb',
                    900: '#ffffff'
                },
                primaryColor: '#34d399',
                primaryLightColor: '#6ee7b7',
                primaryLighterColor: '#a7f3d0',
                primaryLightestColor: 'rgba(52, 211, 153, .2)',
                primaryTextColor: '#030712',
                highlightBg: 'rgba(52, 211, 153, .16)',
                highlightTextColor: 'rgba(255,255,255,.87)',
                highlightFocusBg: 'color-mix(in srgb, var(--primary-500) 24%, transparent)'
            }
        }
    },
    styles: {
        global,
        accordion,
        autocomplete,
        avatar,
        badge,
        blockui,
        breadcrumb,
        button,
        calendar,
        card,
        carousel,
        cascadeselect,
        checkbox,
        chip,
        chips,
        colorpicker,
        confirmdialog,
        confirmpopup,
        contextmenu,
        datatable,
        dataview,
        dialog,
        divider,
        dock,
        dropdown,
        editor,
        fieldset,
        fileupload,
        galleria,
        image,
        inlinemessage,
        inplace,
        inputgroup,
        inputnumber,
        inputswitch,
        inputtext,
        listbox,
        megamenu,
        menu,
        menubar,
        message,
        multiselect,
        orderlist,
        organizationchart,
        overlaypanel,
        paginator,
        panel,
        panelmenu,
        password,
        picklist,
        progressbar,
        progressspinner,
        radiobutton,
        rating,
        scrollpanel,
        scrolltop,
        selectbutton,
        sidebar,
        skeleton,
        slider,
        speeddial,
        splitbutton,
        splitter,
        steps,
        tabmenu,
        tabview,
        tag,
        terminal,
        tieredmenu,
        timeline,
        toast,
        togglebutton,
        toolbar,
        tooltip,
        tree,
        treeselect,
        treetable
    }
};
